[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[server]
headless = true
port = 8501

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
